# numpy 3D

In [1]:
import numpy as np

In [2]:
arr3d = np.arange(50).reshape(5,2,5)

In [3]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [4]:
arr3d.ndim

3

In [5]:
arr3d=arr3d.reshape(2,5,5)

In [6]:
arr3d[1,2,3]

38

In [7]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [8]:
arr3d[1,2:4,1:3]

array([[36, 37],
       [41, 42]])

In [9]:
arr3d[0,2:,4] # you did slicing on row only so you got row

array([14, 19, 24])

In [10]:
arr3d[0,2:,4:] # you did slicing on row,coloumb only so you got row,and coloumb

array([[14],
       [19],
       [24]])

In [11]:
arr3d[0:1,2:,4:] # you did slicing on three parameters so answer is 3d

array([[[14],
        [19],
        [24]]])

In [12]:
# jis par slice hogi uski dimension aigi

In [13]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [14]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

In [15]:
import pandas as pd

In [16]:
obj=pd.Series([0,1,2,3])

In [17]:
obj

0    0
1    1
2    2
3    3
dtype: int64

In [18]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
obj.values

array([0, 1, 2, 3])

In [20]:
obj1 = pd.Series([13,25,56,85],index=["a","b","c","d"])

In [21]:
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [22]:
obj1["d"]

85

In [23]:
obj1["c"]=100

In [24]:
obj1["c"]

100

In [25]:
del obj1["c"]

In [26]:
obj1

a    13
b    25
d    85
dtype: int64

In [27]:
obj1["z"]=100

In [28]:
obj1

a     13
b     25
d     85
z    100
dtype: int64

In [29]:
index=[1,2,3,4,5,6]
obj2 = pd.Series(["apple","🍊 ",1,2,3,4],index= index)

In [30]:
obj2

1    apple
2       🍊 
3        1
4        2
5        3
6        4
dtype: object

In [31]:
obj2.index

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [32]:
obj2.values

array(['apple', '🍊 ', 1, 2, 3, 4], dtype=object)

In [33]:
obj2[[3,5,1]]

3        1
5        3
1    apple
dtype: object

In [34]:
obj2*2

1    appleapple
2          🍊 🍊 
3             2
4             4
5             6
6             8
dtype: object

In [35]:
obj2 == "orange" # same as numpy 

1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [36]:
# if you put aboves series in index you will get ans for these inwhich value is true

In [37]:
obj2[obj2==2]

4    2
dtype: object

In [38]:
s1=pd.Series([100,200,300,400],index=["hun","2h","3h","4h"])

In [39]:
s1

hun    100
2h     200
3h     300
4h     400
dtype: int64

In [40]:
"6h"in s1

False

In [41]:
"3h" in s1

True

In [52]:
sdata = {"a":100,"b":200,"c":300,"d":400}

In [53]:
# you can even pass dictionaries in series and keys will become index and values will becomes values
s2 = pd.Series(sdata)

In [54]:
s2

a    100
b    200
c    300
d    400
dtype: int64

In [55]:
s2.index = [1,2,3,4]

In [56]:
s2

1    100
2    200
3    300
4    400
dtype: int64

In [57]:
alpha = ["a","b","c","e"]

In [58]:
s3 =pd.Series(sdata,alpha) # only take those values from dictionary whose index match with given index

In [59]:
s3

a    100.0
b    200.0
c    300.0
e      NaN
dtype: float64

In [60]:
pd.isnull(s3)

a    False
b    False
c    False
e     True
dtype: bool

In [61]:
pd.notnull(s3)

a     True
b     True
c     True
e    False
dtype: bool



# DataFrames

In [62]:
data = {"saad":[1,2,3,4],"ali":[5,6,7,8],'Ahmed':[1,2,3,4]}


In [63]:
df = pd.DataFrame(data)

In [64]:
df

saad  ali  Ahmed
0     1    5      1
1     2    6      2
2     3    7      3
3     4    8      4

In [65]:
df.head()

saad  ali  Ahmed
0     1    5      1
1     2    6      2
2     3    7      3
3     4    8      4

In [71]:
df.tail(10)

saad  ali  Ahmed
0     1    5      1
1     2    6      2
2     3    7      3
3     4    8      4

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
saad     4 non-null int64
ali      4 non-null int64
Ahmed    4 non-null int64
dtypes: int64(3)
memory usage: 176.0 bytes


In [69]:
df.describe()

saad       ali     Ahmed
count  4.000000  4.000000  4.000000
mean   2.500000  6.500000  2.500000
std    1.290994  1.290994  1.290994
min    1.000000  5.000000  1.000000
25%    1.750000  5.750000  1.750000
50%    2.500000  6.500000  2.500000
75%    3.250000  7.250000  3.250000
max    4.000000  8.000000  4.000000

In [72]:
frame = pd.DataFrame(data,columns=["saad","ali","total"],index=[1,2,3,4])

In [73]:
frame

saad  ali total
1     1    5   NaN
2     2    6   NaN
3     3    7   NaN
4     4    8   NaN

In [74]:
frame["debt"] = 100

In [75]:
frame

saad  ali total  debt
1     1    5   NaN   100
2     2    6   NaN   100
3     3    7   NaN   100
4     4    8   NaN   100

In [76]:
frame.total =100

In [77]:
frame

saad  ali  total  debt
1     1    5    100   100
2     2    6    100   100
3     3    7    100   100
4     4    8    100   100

In [78]:
frame.total = [100,200,300,400]

In [79]:
frame

saad  ali  total  debt
1     1    5    100   100
2     2    6    200   100
3     3    7    300   100
4     4    8    400   100

In [81]:
frame.debt = range(4)

In [83]:
frame

saad  ali  total  debt
1     1    5    100     0
2     2    6    200     1
3     3    7    300     2
4     4    8    400     3

In [85]:
frame.columns

Index(['saad', 'ali', 'total', 'debt'], dtype='object')

In [88]:
frame.values

array([[  1,   5, 100,   0],
       [  2,   6, 200,   1],
       [  3,   7, 300,   2],
       [  4,   8, 400,   3]])

In [89]:
frame[["saad","debt"]]

saad  debt
1     1     0
2     2     1
3     3     2
4     4     3

In [91]:
frame.iloc[3] # picks values from 3 index
#frame.loc["three"] # picks values from three index of dtype string

saad       4
ali        8
total    400
debt       3
Name: 4, dtype: int64

In [92]:
val = pd.Series([1.2,1.3,1.5],index=[2,3,1])

In [93]:
frame["debt"] = val

In [94]:
frame

saad  ali  total  debt
1     1    5    100   1.5
2     2    6    200   1.2
3     3    7    300   1.3
4     4    8    400   NaN

In [95]:
frame["else"] = frame.saad == 1

In [96]:
frame

saad  ali  total  debt   else
1     1    5    100   1.5   True
2     2    6    200   1.2  False
3     3    7    300   1.3  False
4     4    8    400   NaN  False

In [189]:
score = {"python1":[100,32,50,68,97,84,89],
         "python2":[45,50,75,95,100,28,69],
         "AI for EO":[45,78,33,76,90,98,78]
        
        }

In [190]:
frame2 = pd.DataFrame(score)

In [191]:
frame2

python1  python2  AI for EO
0      100       45         45
1       32       50         78
2       50       75         33
3       68       95         76
4       97      100         90
5       84       28         98
6       89       69         78

In [192]:
frame2["total"] = frame2.python1+frame2.python2+frame2["AI for EO"]

In [193]:
frame2

python1  python2  AI for EO  total
0      100       45         45    190
1       32       50         78    160
2       50       75         33    158
3       68       95         76    239
4       97      100         90    287
5       84       28         98    210
6       89       69         78    236

In [194]:
frame2["status"]=["pass"if i >=200 else "fail" for i in frame2.total ]

In [195]:
frame2

python1  python2  AI for EO  total status
0      100       45         45    190   fail
1       32       50         78    160   fail
2       50       75         33    158   fail
3       68       95         76    239   pass
4       97      100         90    287   pass
5       84       28         98    210   pass
6       89       69         78    236   pass

In [196]:

a=frame2[["python1","python2","AI for EO"]]
a= [ "pass" if all(i >=33 ) else "fail" for i in frame2[["python1","python2","AI for EO"]].values]
a

['pass', 'fail', 'pass', 'pass', 'pass', 'fail', 'pass']

In [197]:
frame2["status"] = a
frame2

python1  python2  AI for EO  total status
0      100       45         45    190   pass
1       32       50         78    160   fail
2       50       75         33    158   pass
3       68       95         76    239   pass
4       97      100         90    287   pass
5       84       28         98    210   fail
6       89       69         78    236   pass