# numpy 3D

In [1]:
import numpy as np

In [4]:
arr3d = np.arange(50).reshape(5,2,5)

In [5]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
arr3d.ndim

3

In [12]:
arr3d=arr3d.reshape(2,5,5)

In [13]:
arr3d[1,2,3]

38

In [15]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [18]:
arr3d[1,2:4,1:3]

array([[36, 37],
       [41, 42]])

In [19]:
arr3d[0,2:,4] # you did slicing on row only so you got row

array([14, 19, 24])

In [20]:
arr3d[0,2:,4:] # you did slicing on row,coloumb only so you got row,and coloumb

array([[14],
       [19],
       [24]])

In [21]:
arr3d[0:1,2:,4:] # you did slicing on three parameters so answer is 3d

array([[[14],
        [19],
        [24]]])

In [22]:
# jis par slice hogi uski dimension aigi

In [23]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [24]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

In [25]:
import pandas as pd

In [31]:
obj=pd.Series([0,1,2,3])

In [32]:
obj

0    0
1    1
2    2
3    3
dtype: int64

In [33]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [35]:
obj.values

array([0, 1, 2, 3])

In [36]:
obj1 = pd.Series([13,25,56,85],index=["a","b","c","d"])

In [37]:
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [38]:
obj1["d"]

85

In [39]:
obj1["c"]=100

In [40]:
obj1["c"]

100

In [41]:
del obj1["c"]

In [42]:
obj1

a    13
b    25
d    85
dtype: int64

In [43]:
obj1["z"]=100

In [44]:
obj1

a     13
b     25
d     85
z    100
dtype: int64

In [50]:
index=[1,2,3,4,5,6]
obj2 = pd.Series(["apple","🍊 ",1,2,3,4],index= index)

In [51]:
obj2

1    apple
2       🍊 
3        1
4        2
5        3
6        4
dtype: object

In [52]:
obj2.index

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [53]:
obj2.values

array(['apple', '🍊 ', 1, 2, 3, 4], dtype=object)

<bound method Series.count of 1    apple
2       🍊 
3        1
4        2
5        3
6        4
dtype: object>

In [54]:
obj2[[3,5,1]]

3        1
5        3
1    apple
dtype: object

In [55]:
obj2*2

1    appleapple
2          🍊 🍊 
3             2
4             4
5             6
6             8
dtype: object

In [57]:
obj2 == "orange" # same as numpy 

1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [58]:
# if you put aboves series in index you will get ans for these inwhich value is true

In [60]:
obj2[obj2==2]

4    2
dtype: object

In [62]:
s1=pd.Series([100,200,300,400],index=["hun","2h","3h","4h"])

In [63]:
s1

hun    100
2h     200
3h     300
4h     400
dtype: int64

In [64]:
"6h"in s1

False

In [65]:
"3h" in s1

True

In [70]:
sdata = {"a":100,"b":200,"c":300,"d":400}

In [71]:
# you can even pass dictionaries in series and keys will become index and values will becomes values
s2 = pd.Series(sdata)

In [72]:
s2

a    100
b    200
c    300
d    400
dtype: int64

In [73]:
s2.index = [1,2,3,4]

In [74]:
s2

1    100
2    200
3    300
4    400
dtype: int64

In [81]:
alpha = ["a","b","c","e"]

In [82]:
s3 =pd.Series(sdata,alpha) # only take those values from dictionary whose index match with given index

In [83]:
s3

a    100.0
b    200.0
c    300.0
e      NaN
dtype: float64

In [90]:
pd.isnull(s3)

a    False
b    False
c    False
e     True
dtype: bool

In [91]:
pd.notnull(s3)

a     True
b     True
c     True
e    False
dtype: bool